### ISSUE TITLE
Custom Repository support 

### ISSUE THREAD

**Issue by hantsy** [devniel/nestjs-typeorm-testing#9]
Nestjs/TypesORM supports custom `Repository` like this.

```typescript
@EntityRepository(UserEntity)
export class UserRepository extends Repository<UserEntity> {
  findByEmail(email: string): Promise<UserEntity> {
    return this.findOne({ email: email });
  }
}
```

And register in the `TypeOrmModule.forFeature([UserRepository])`.

I want to verify the `findOne` is called from the parent  `Repository<User>` and when calling `findEmail` method.

https://stackoverflow.com/questions/67580233/how-to-test-custom-repository-in-nestjs-typeorm-applications

**Comment by devniel** [comment]
Hello @hantsy , I think there is no available parent `Repository` instance to spy, but only the inherited created instance, you can test if `UserRepository.findOne` was called if calling `findByEmail`.

```ts
import { Test, TestingModule } from '@nestjs/testing';
import { TypeOrmTestModule } from '../lib';
import { User } from './shared/User';
import { getRepositoryToken } from '@nestjs/typeorm';
import { UserRepository } from './shared/UserCustomRepository';

describe('Custom repository provided', () => {
  let usersCustomRepository: UserRepository;

  beforeAll(async () => {
    const module: TestingModule = await Test.createTestingModule({
      imports: [TypeOrmTestModule.forTest([UserRepository])],
      providers: [UserRepository],
    }).compile();
    usersCustomRepository = module.get(getRepositoryToken(User));
  });

  it('repository for access entity should be defined', () => {
    expect(usersCustomRepository).toBeDefined();
  });

  it('should call the parent class method findOne() when calling instance findByEmail()', async () => {
    const spyfindOne = jest.spyOn(usersCustomRepository, 'findOne');
    await usersCustomRepository.findByEmail('test');
    expect(spyfindOne).toHaveBeenCalledTimes(1);
  });
});
```

**Comment by hantsy** [comment]
@devniel  Thanks for the example.  

But there is still a little issue in my example.

My entity name is `UserEntity`, the repository is `UserRepository`, the `module.get(getRepositoryToken(UserEntity))` will search `UserEntityRepository`.

When running the tests, and got the following exceptions.

```bash
Nest could not find UserEntityRepository element (this provider does not exist in the current context)
```

**Comment by devniel** [comment]
Hello @hantsy ,

it's related to @nestjs/typeorm, maybe we can create a PR for that, specifically here https://github.com/nestjs/typeorm/blob/8c55173a70ec2412f4d0445435223ec7c13b0629/lib/common/typeorm.utils.ts#L25

The workaround that I found is by using Object.defineProperty, (I tried with @Entity{ name: 'User' }  but it didn't work).

```ts
import { Entity, BaseEntity, PrimaryGeneratedColumn, Column } from 'typeorm';

@Entity({
  name: 'User' // this didn't work
})
export class UserEntity extends BaseEntity {

  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @Column('text', { unique: true })
  username: string;

  @Column('text', { unique: true })
  email: string;

  @Column()
  password: string;
}

Object.defineProperty(UserEntity, "name", { writable: true });

// @ts-ignore
UserEntity.name = "User"; // this works :) 

````

**Comment by hantsy** [comment]
The name in the  `@Entity({name="uesrs"})` will apply the name to the table
generated.

In the original Java EE JPA spec, the entity name and table name are
different things.

*Hantsy Bai*

Self-employed consultant, fullstack developer, agile coach

GitHub: https://github.com/hantsy

Twitter: ***@***.***
Medium: ***@***.***

**Comment by devniel** [comment]
Yes, I was expecting that, so the last approach of `Object.defineProperty` should fix the problem, given that the "repository search" looks for Function.name; but, I'm not sure if it's also used for creating the tables, I will try it outside of the project.
